version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: America/New_York
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: disabled